### PR TITLE
Base Redesign

### PR DESCRIPTION
**Pull request by TheNocturnalDev**
Full redesign of Elpis, working up cleaning up unused old code/libs

### CODE REVIEW

**Comment by TheNocturnalDev** [comment]
Capture
Capture1
Capture2

**Comment by ScottamDendar** [comment]
I don't know how active this project is anymore, specially considering the note in the ReadMe.  Perhaps fork it or reach out to adammhaile?

**Comment by adammhaile** [comment]
Sorry I've been away. Will look at this today :)

**Comment by adammhaile** [comment]
@SymphonicDev1 merged... I'll add you as an admin and send you some details soon via email about how to do a release

**Pull request merged**
