### PR TITLE
Updated Settings view UI to improve app consistency

### PR DESCRIPTION
**Pull request by daxit**
Cleaned up settings interface to reflect the newer modern design of the app
See #123

### CODE REVIEW

**Comment by Wires77** [comment]
Thanks for the pull request.  I'll take a look this weekend when I have some time.

**Comment by daxit** [comment]
I have made a few more changes to improve overall app design.

1. The blue hovers and highlights are replaced with much more relevant black variant highlights.

2. Icons have been replaced with transparent versions. This is the best hack I could figure out for now in order to support various themes. I would eventually like to use svg (Paths) so that the colors can be changed directly. I also removed the thumbs_up and thumbs_down png, since they looked like leftovers. thumbUp and thumbDown are the new icons.

3. Minimum height has been set to 100. This is an easy way to allow a mini version of the current player until a better solution is implemented.

image

This is the kind of themeing to expect once the feature is implemented (I changed 4 hex color values to achieve the result) :
image

**Comment by daxit** [comment]
I added a few more changes regarding controls:
- updated volume slider to match design
- volume slider no longer covers other controls when open
- play and next moved to left to create space for volume
- radio name and progress bar swapped rows
- minor spacing and sizing adjustments

image

**Comment by Wires77** [comment]
I see the icon changes in the commits and my local copy, but not the new volume slider or icon location changes.  Perhaps you need to push those still?

Also, it looks like increasing the size of the thumbsLove icon cut off part of the knuckle (and now that I'm comparing the two, part of the wrist of the thumbsDown icon as well):

image

image

**Comment by daxit** [comment]
I have yet to push my latest changes. I will try to address the icon cutoff in that push. I also want to see if I can add in theme support before this branch is merged to master.

**Pull request closed without merging**
